"""C and C++ DSA and System Design pattern definitions.

Bounded "C-family lite" pilot (roadmap item 8, path (a)). Every signal
is anchored on an ``#include`` path or a blanked-code identifier; macro
bodies, string literals, and comments are never evidence. Design
patterns require corroboration (``min_signals`` 2) unless a
single third-party include is unambiguous.

Every pattern ID exists in the Python catalog (regression-locked).
"""

from __future__ import annotations

from .production_patterns import PRODUCTION_DSA_PATTERNS, production_design_patterns

C_DSA_PATTERNS = {
    "hash_map": {
        "imports": ["unordered_map"],
        "identifiers": [
            "unordered_map",
            "hash_map",
            "hashmap",
            "hashtable",
            "absl::flat_hash_map",
            "flat_hash_map",
        ],
        "min_signals": 1,
        "description": "Hash-based data structures for O(1) lookups",
    },
    "set_operations": {
        "imports": ["unordered_set"],
        "identifiers": [
            "unordered_set",
            "std::set",
            "set_intersection",
            "set_union",
            "set_difference",
            "bitset",
        ],
        "min_signals": 1,
        "description": "Set operations for unique elements and fast membership",
    },
    "sorting": {
        "identifiers": [
            "std::sort",
            "qsort",
            "stable_sort",
            "partial_sort",
            "nth_element",
            "mergesort",
            "quicksort",
        ],
        "min_signals": 1,
        "description": "Sorting algorithms and ordered operations",
    },
    "binary_search": {
        "identifiers": ["binary_search", "lower_bound", "upper_bound", "bsearch", "equal_range"],
        "text": ["mid =", "lo, hi", "low, high", ">> 1"],
        "min_signals": 2,
        "description": "Binary search for O(log n) lookups",
    },
    "graph_traversal": {
        "identifiers": [
            "bfs",
            "dfs",
            "visited",
            "neighbors",
            "neighbours",
            "adjacency",
            "adj",
            "graph",
        ],
        "min_signals": 2,
        "description": "Graph traversal algorithms (BFS/DFS)",
    },
    "dynamic_programming": {
        # A bare `dp` variable meant "dependency plugin" in drogon; require
        # the table access or a memoization name.
        "identifiers": ["memo", "memoize", "memoization", "memo_table", "dp_table"],
        "text": ["dp["],
        "min_signals": 1,
        "description": "Dynamic programming and memoization",
    },
    "tree_structures": {
        "identifiers": [
            "treenode",
            "tree_node",
            "binarytree",
            "binary_tree",
            "btree",
            "avltree",
            "rbtree",
            "std::map",
            "multimap",
        ],
        "min_signals": 1,
        "description": "Tree data structures (binary, AVL, red-black, B-tree)",
    },
    "linked_list": {
        "identifiers": [
            "linkedlist",
            "linked_list",
            "listnode",
            "list_node",
            "std::list",
            "forward_list",
            "list_head",
            "next_ptr",
        ],
        "min_signals": 1,
        "description": "Linked list data structures",
    },
    "queue_stack": {
        "identifiers": [
            "std::queue",
            "std::stack",
            "std::deque",
            "deque",
            "push_back",
            "pop_back",
            "push_front",
            "pop_front",
            "enqueue",
            "dequeue",
            "ring_buffer",
            "ringbuffer",
            "circular_buffer",
        ],
        "min_signals": 2,
        "description": "Queue and stack data structures",
    },
    "heap_priority": {
        "identifiers": [
            "priority_queue",
            "make_heap",
            "push_heap",
            "pop_heap",
            "minheap",
            "maxheap",
            "min_heap",
            "max_heap",
            "heapify",
        ],
        "min_signals": 1,
        "description": "Heap and priority queue structures",
    },
    "trie": {
        "identifiers": ["trie", "trienode", "trie_node", "prefixtree", "prefix_tree"],
        "min_signals": 1,
        "description": "Trie (prefix tree) for string operations",
    },
    "union_find": {
        "identifiers": [
            "unionfind",
            "union_find",
            "disjointset",
            "disjoint_set",
            "find_parent",
            "find_root",
            "findparent",
            "findroot",
            "path_compression",
            "union_by_rank",
        ],
        "min_signals": 2,
        "description": "Union-Find (Disjoint Set Union) data structure",
    },
    "topological_sort": {
        "identifiers": [
            "topologicalsort",
            "topological_sort",
            "toposort",
            "topological",
            "indegree",
            "in_degree",
        ],
        "min_signals": 1,
        "description": "Topological sorting for DAGs",
    },
    "sliding_window": {
        "identifiers": ["slidingwindow", "sliding_window", "window_start", "window_end"],
        "min_signals": 1,
        "description": "Sliding window technique",
    },
    "two_pointers": {
        "identifiers": [
            "twopointer",
            "twopointers",
            "two_pointers",
            "left_pointer",
            "right_pointer",
            "slow_pointer",
            "fast_pointer",
            "tortoise",
            "hare",
        ],
        "min_signals": 2,
        "description": "Two-pointer technique",
    },
    "backtracking": {
        "identifiers": ["backtrack", "backtracking"],
        "min_signals": 1,
        "description": "Backtracking algorithms",
    },
    "segment_tree": {
        "identifiers": ["segmenttree", "segment_tree", "segtree"],
        "min_signals": 1,
        "description": "Segment tree for range queries",
    },
    "fenwick_tree": {
        "identifiers": [
            "fenwick",
            "fenwicktree",
            "fenwick_tree",
            "binaryindexedtree",
            "binary_indexed_tree",
            "bit_tree",
        ],
        "min_signals": 1,
        "description": "Fenwick tree (Binary Indexed Tree)",
    },
    "lru_cache_manual": {
        "identifiers": ["lru", "lrucache", "lru_cache"],
        "min_signals": 1,
        "description": "Manual LRU cache implementation",
    },
    "bloom_filter": {
        "identifiers": ["bloomfilter", "bloom_filter"],
        "min_signals": 1,
        "description": "Bloom filter probabilistic data structure",
    },
    "dijkstra": {
        "identifiers": [
            "dijkstra",
            "shortestpath",
            "shortest_path",
            "bellmanford",
            "bellman_ford",
            "astar",
            "a_star",
        ],
        "min_signals": 1,
        "description": "Shortest path algorithms",
    },
    "minimum_spanning_tree": {
        "identifiers": ["kruskal", "prim", "spanningtree", "spanning_tree"],
        "min_signals": 1,
        "description": "Minimum spanning tree algorithms",
    },
    "monotonic_stack": {
        "identifiers": ["monotonicstack", "monotonic_stack", "monotonic"],
        "min_signals": 1,
        "description": "Monotonic stack/queue technique",
    },
    "interval_operations": {
        # Bare "interval" is TCP keepalive / timer vocabulary in C; require
        # the algorithmic forms.
        "identifiers": [
            "intervals",
            "mergeintervals",
            "merge_intervals",
            "interval_tree",
            "overlapping_intervals",
        ],
        "min_signals": 1,
        "description": "Interval merging and scheduling",
    },
}

C_DESIGN_PATTERNS = {
    "api_design": {
        "imports": [
            "grpcpp",
            "grpc/grpc.h",
            "crow",
            "pistache",
            "httplib.h",
            "boost/beast",
            "drogon",
            "oatpp",
            "restinio",
            "microhttpd.h",
            "civetweb",
            "mongoose.h",
            "userver",
        ],
        "identifiers": ["crow_route", "http_response", "httpserver", "http_server"],
        "min_signals": 1,
        "description": "HTTP/RPC API design",
    },
    "database_orm": {
        "imports": [
            "sqlite3.h",
            "libpq-fe.h",
            "pqxx",
            "mysql.h",
            "mysql/mysql.h",
            "soci",
            "sqlpp11",
            "odb/",
            "rocksdb",
            "leveldb",
            "lmdb.h",
            "mongocxx",
            "cassandra.h",
        ],
        "min_signals": 1,
        "description": "Database access layers",
    },
    "caching": {
        "imports": ["hiredis", "sw/redis++", "libmemcached"],
        "identifiers": ["cache", "memcache", "redis", "cache_get", "cache_put", "cache_set", "ttl"],
        "min_signals": 2,
        "description": "Caching layers",
    },
    "message_queue": {
        "imports": [
            "librdkafka",
            "rdkafka.h",
            "rdkafkacpp.h",
            "zmq.h",
            "zmq.hpp",
            "amqp",
            "SimpleAmqpClient",
            "nats.h",
            "mosquitto.h",
            "paho",
            "pulsar",
        ],
        "identifiers": ["producer", "consumer", "topic", "broker", "publish", "subscribe"],
        "min_signals": 2,
        "description": "Message queue integration",
    },
    "factory_pattern": {
        "identifiers": [
            "factory",
            "create_instance",
            "createinstance",
            "make_unique",
            "make_shared",
            "builder",
        ],
        "min_signals": 2,
        "description": "Factory pattern",
    },
    "singleton_pattern": {
        "identifiers": ["singleton", "getinstance", "get_instance", "instance"],
        "text": ["static instance", "static auto instance", "static auto& instance", "call_once"],
        "min_signals": 2,
        "description": "Singleton pattern",
    },
    "dependency_injection": {
        "imports": ["boost/di.hpp", "fruit/fruit.h", "kangaru"],
        "identifiers": ["injector", "inject", "container", "provider"],
        "min_signals": 2,
        "description": "Dependency injection",
    },
    "error_handling": {
        "imports": [
            "stdexcept",
            "exception",
            "system_error",
            "expected",
            "tl/expected",
            "absl/status",
            "outcome",
        ],
        "identifiers": [
            "errno",
            "perror",
            "strerror",
            "std::runtime_error",
            "runtime_error",
            "logic_error",
            "error_code",
            "status",
            "statusor",
            "expected",
            "noexcept",
        ],
        "text": ["try {", "catch (", "catch("],
        "min_signals": 2,
        "description": "Error handling and exceptions",
    },
    "logging": {
        "imports": [
            "spdlog",
            "glog/logging.h",
            "log4cxx",
            "log4cplus",
            "plog",
            "syslog.h",
            "boost/log",
            "loguru",
            "quill",
            "absl/log",
        ],
        "identifiers": [
            "spdlog",
            "syslog",
            "log_info",
            "log_error",
            "log_warn",
            "log_debug",
            "logger",
        ],
        "min_signals": 1,
        "description": "Logging infrastructure",
    },
    "authentication": {
        "imports": [
            "openssl/",
            "jwt-cpp",
            "jwt.h",
            "sodium.h",
            "argon2.h",
            "bcrypt",
            "gnutls",
            "mbedtls",
            "wolfssl",
            "libssh",
            "pam_appl.h",
        ],
        "identifiers": [
            "authenticate",
            "authorize",
            "jwt",
            "oauth",
            "verify_token",
            "hmac",
            "sha256",
            "password_hash",
            "bcrypt",
            "argon2",
        ],
        "min_signals": 2,
        "description": "Authentication and authorization",
    },
    "testing": {
        "imports": [
            "gtest/gtest.h",
            "gmock/gmock.h",
            "catch2",
            "catch.hpp",
            "doctest",
            "boost/test",
            "cmocka.h",
            "unity.h",
            "check.h",
            "cpputest",
            "criterion",
        ],
        "identifiers": [
            "test_case",
            "test_f",
            "test_p",
            "expect_eq",
            "assert_eq",
            "require",
            "section",
            "mock_method",
            "check_equal",
        ],
        "min_signals": 1,
        "description": "Testing infrastructure",
    },
    "microservices": {
        "imports": [
            "grpcpp",
            "google/protobuf",
            "flatbuffers",
            "capnp",
            "thrift",
            "consul",
            "etcd",
        ],
        "identifiers": [
            "service_discovery",
            "servicediscovery",
            "health_check",
            "healthcheck",
            "circuit",
            "grpc",
        ],
        "min_signals": 2,
        "description": "Microservices patterns",
    },
    "repository_pattern": {
        "identifiers": [
            "repository",
            "repo",
            "find_by_id",
            "findbyid",
            "find_all",
            "findall",
            "save",
            "dao",
        ],
        "min_signals": 2,
        "description": "Repository pattern",
    },
    "config_management": {
        "imports": [
            "yaml-cpp",
            "toml++",
            "toml.hpp",
            "inih",
            "ini.h",
            "boost/program_options",
            "cxxopts",
            "gflags",
            "absl/flags",
            "CLI/CLI.hpp",
            "getopt.h",
            "nlohmann/json",
            "rapidjson",
            "simdjson",
        ],
        "identifiers": [
            "getenv",
            "secure_getenv",
            "config",
            "settings",
            "parse_args",
            "program_options",
            "cxxopts",
            "define_flag",
        ],
        "min_signals": 2,
        "description": "Configuration management",
    },
}

# Scoring policy 2.0.0: production-systems and GoF patterns, merged from the
# shared specs with C/C++'s idiomatic libraries and primitives. Includes are
# the strongest evidence in C-family code, so most anchors are header paths.
C_DSA_PATTERNS.update(PRODUCTION_DSA_PATTERNS)
C_DESIGN_PATTERNS.update(
    production_design_patterns(
        imports={
            "resilience": ["resilience", "cpp_redis", "backoff"],
            "rate_limiting": ["token_bucket", "ratelimit"],
            "observability": [
                "opentelemetry/",
                "prometheus/",
                "jaeger",
                "statsd",
                "sentry.h",
                "absl/log",
                "perfetto",
            ],
            "event_sourcing_cqrs": ["eventstore"],
            "pagination": [],
            "concurrency": [
                "thread",
                "mutex",
                "atomic",
                "condition_variable",
                "future",
                "pthread.h",
                "semaphore",
                "shared_mutex",
                "tbb/",
                "oneapi/tbb",
                "omp.h",
                "boost/asio",
                "boost/thread",
                "folly/",
                "libuv",
                "uv.h",
                "event2/",
                "liburing",
                "coroutine",
                "boost/fiber",
                "cppcoro",
                "seastar",
                "taskflow",
                "concurrentqueue",
            ],
        },
        identifiers={
            "concurrency": [
                "std::thread",
                "pthread_create",
                "pthread_mutex_lock",
                "std::mutex",
                "lock_guard",
                "unique_lock",
                "scoped_lock",
                "std::atomic",
                "atomic_fetch_add",
                "condition_variable",
                "std::async",
                "std::future",
                "promise",
                "thread_pool",
                "threadpool",
                "io_context",
                "co_await",
                "co_return",
                "epoll_wait",
                "kqueue",
                "spinlock",
                "rwlock",
            ],
            "resilience": [
                "retry",
                "backoff",
                "circuit_breaker",
                "circuitbreaker",
                "fallback",
                "timeout",
                "deadline",
            ],
            "idempotency": ["idempotency_key", "idempotent", "dedupe", "dedup", "seen_ids"],
            "observability": [
                "trace_id",
                "span",
                "tracer",
                "counter",
                "histogram",
                "gauge",
                "metrics",
            ],
            "rate_limiting": [
                "rate_limit",
                "ratelimit",
                "token_bucket",
                "leaky_bucket",
                "throttle",
            ],
        },
        text={
            "concurrency": [
                "std::thread",
                "std::mutex",
                "std::atomic",
                "co_await",
                "pthread_create(",
            ],
        },
        min_signals={"concurrency": 2},
    )
)
