"""Rust DSA and System Design pattern definitions (experimental pilot).

Anchors are ``use`` paths (crate roots and full paths, lower-cased) and
blanked-code identifiers; string literals, comments and macro bodies are
never evidence. Rust's standard library is unusually explicit about data
structures (``BinaryHeap``, ``BTreeMap``, ``VecDeque``), so many DSA
signals are single-identifier anchors; design patterns lean on the crate
ecosystem (tokio, serde, sqlx, tracing, axum …).

Every pattern ID exists in the Python catalog (regression-locked by
``tests/test_fairness.py``).
"""

from __future__ import annotations

from .production_patterns import PRODUCTION_DSA_PATTERNS, production_design_patterns

RUST_DSA_PATTERNS = {
    "hash_map": {
        "imports": ["std::collections::hashmap", "hashbrown", "indexmap", "fxhash", "ahash"],
        "identifiers": ["hashmap", "hashset", "indexmap", "fxhashmap", "ahashmap", "dashmap"],
        "min_signals": 1,
        "description": "Hash-based data structures for O(1) lookups",
    },
    "set_operations": {
        "imports": ["std::collections::hashset", "std::collections::btreeset"],
        "identifiers": ["hashset", "btreeset", "intersection", "union", "difference", "is_subset"],
        "min_signals": 1,
        "description": "Set operations for unique elements and fast membership",
    },
    "sorting": {
        "identifiers": [
            "sort",
            "sort_by",
            "sort_by_key",
            "sort_unstable",
            "sort_unstable_by",
            "binary_heap",
        ],
        "text": ["sort_by_key(", "sort_unstable("],
        "min_signals": 1,
        "description": "Sorting algorithms and ordered operations",
    },
    "binary_search": {
        "identifiers": [
            "binary_search",
            "binary_search_by",
            "binary_search_by_key",
            "partition_point",
        ],
        "min_signals": 1,
        "description": "Binary search over ordered data",
    },
    "heap_priority": {
        "imports": ["std::collections::binaryheap", "priority-queue", "priority_queue"],
        "identifiers": ["binaryheap", "priorityqueue", "reverse", "peek_mut"],
        "min_signals": 1,
        "description": "Heap / priority queue usage",
    },
    "queue_stack": {
        "imports": [
            "std::collections::vecdeque",
            "std::collections::linkedlist",
            "crossbeam_deque",
        ],
        "identifiers": ["vecdeque", "push_back", "pop_front", "push_front", "pop_back", "deque"],
        "min_signals": 1,
        "description": "Queue and stack processing",
    },
    "linked_list": {
        "imports": ["std::collections::linkedlist"],
        "identifiers": ["linkedlist", "listnode", "next_node", "prev_node"],
        "identifier_contains": ["_node"],
        "min_signals": 1,
        "description": "Linked-list structures",
    },
    "tree_structures": {
        "imports": ["std::collections::btreemap", "petgraph", "indextree", "slab_tree", "ego_tree"],
        "identifiers": [
            "btreemap",
            "treenode",
            "rb_tree",
            "left",
            "right",
            "subtree",
            "inorder",
            "preorder",
        ],
        "min_signals": 2,
        "description": "Tree data structures",
    },
    "graph_traversal": {
        "imports": ["petgraph", "pathfinding"],
        "identifiers": [
            "bfs",
            "dfs",
            "adjacency",
            "adj",
            "visited",
            "neighbors",
            "graphmap",
            "digraph",
        ],
        "min_signals": 2,
        "description": "Graph traversal",
    },
    "dijkstra": {
        "imports": ["pathfinding::directed::dijkstra", "petgraph::algo::dijkstra"],
        "identifiers": ["dijkstra", "shortest_path", "astar", "bellman_ford"],
        "min_signals": 1,
        "description": "Shortest-path algorithms",
    },
    "dynamic_programming": {
        "identifiers": [
            "dp",
            "memo",
            "memoize",
            "memoized",
            "memoization",
            "knapsack",
            "lcs",
            "cached",
        ],
        "imports": ["cached", "memoize"],
        "min_signals": 1,
        "description": "Dynamic programming and memoization",
    },
    "two_pointers": {
        "identifiers": ["left", "right", "lo", "hi", "slow", "fast", "two_pointer", "two_pointers"],
        "text": ["left < right", "lo < hi", "lo <= hi"],
        "min_signals": 2,
        "description": "Two-pointer techniques",
    },
    "sliding_window": {
        "identifiers": ["window", "window_start", "window_end", "windows", "chunks", "window_size"],
        "text": [".windows(", ".chunks("],
        "min_signals": 1,
        "description": "Sliding-window computation",
    },
    "prefix_sum": PRODUCTION_DSA_PATTERNS["prefix_sum"],
    "monotonic_stack": {
        "identifiers": [
            "monotonic_stack",
            "mono_stack",
            "next_greater",
            "prev_greater",
            "next_smaller",
        ],
        "min_signals": 1,
        "description": "Monotonic stack",
    },
    "interval_operations": {
        "identifiers": ["intervals", "merge_intervals", "interval", "rangeinclusive", "overlaps"],
        "imports": ["intervallum", "rangemap", "iset"],
        "text": ["intervals.sort", "sort_by_key(|i| i.start)"],
        "min_signals": 1,
        "description": "Interval merging and overlap detection",
    },
    "backtracking": {
        "identifiers": [
            "backtrack",
            "backtracking",
            "permute",
            "permutations",
            "subsets",
            "n_queens",
        ],
        "imports": ["itertools::permutations"],
        "min_signals": 1,
        "description": "Backtracking search",
    },
    "trie": {
        "imports": ["radix_trie", "trie-rs", "trie_rs", "fst", "qp_trie", "patricia_tree"],
        "identifiers": [
            "trie",
            "trienode",
            "prefix_tree",
            "radix_tree",
            "insert_word",
            "starts_with",
        ],
        "min_signals": 1,
        "description": "Trie / prefix tree",
    },
    "union_find": {
        "imports": ["petgraph::unionfind", "union_find", "disjoint-sets", "disjoint_sets"],
        "identifiers": ["unionfind", "union_find", "disjoint_set", "find_root", "find_parent"],
        "text": ["fn find(", "fn union("],
        "min_signals": 1,
        "description": "Union-find / disjoint set",
    },
    "topological_sort": {
        "imports": ["petgraph::algo::toposort", "topological-sort", "topological_sort"],
        "identifiers": [
            "toposort",
            "topological_sort",
            "topo_sort",
            "in_degree",
            "indegree",
            "kahn",
        ],
        "min_signals": 1,
        "description": "Topological ordering",
    },
    "minimum_spanning_tree": {
        "imports": ["petgraph::algo::min_spanning_tree"],
        "identifiers": ["min_spanning_tree", "kruskal", "prim", "mst", "spanning_tree"],
        "min_signals": 1,
        "description": "Minimum spanning tree",
    },
    "segment_tree": {
        "identifiers": ["segment_tree", "segtree", "seg_tree", "lazy_propagation", "range_query"],
        "min_signals": 1,
        "description": "Segment tree",
    },
    "fenwick_tree": {
        "identifiers": [
            "fenwick",
            "fenwick_tree",
            "bit_tree",
            "binary_indexed_tree",
            "prefix_update",
        ],
        "min_signals": 1,
        "description": "Fenwick / binary indexed tree",
    },
    "lru_cache_manual": {
        "imports": ["lru", "moka", "quick_cache", "mini-moka", "mini_moka"],
        "identifiers": [
            "lrucache",
            "lru_cache",
            "lru",
            "evict",
            "eviction",
            "capacity",
            "recently_used",
        ],
        "min_signals": 1,
        "description": "LRU cache",
    },
    "bloom_filter": {
        "imports": [
            "bloomfilter",
            "bloom",
            "probabilistic-collections",
            "growable_bloom_filter",
            "fastbloom",
        ],
        "identifiers": [
            "bloomfilter",
            "bloom_filter",
            "bloom",
            "cuckoo_filter",
            "false_positive_rate",
        ],
        "min_signals": 1,
        "description": "Bloom filter",
    },
    "bit_manipulation": {
        "identifiers": [
            "bitflags",
            "bitvec",
            "bitset",
            "count_ones",
            "leading_zeros",
            "trailing_zeros",
            "bitmask",
        ],
        "imports": ["bitflags", "bitvec", "bit-set", "bit_set", "fixedbitset", "roaring"],
        "text": [".count_ones()", ".leading_zeros()", " & mask", " | mask"],
        "min_signals": 1,
        "description": "Bit manipulation and bitmask techniques",
    },
    "string_matching": {
        "imports": ["regex", "aho-corasick", "aho_corasick", "memchr", "bstr", "strsim"],
        "identifiers": [
            "regex",
            "ahocorasick",
            "kmp",
            "rabin_karp",
            "levenshtein",
            "memmem",
            "find_iter",
        ],
        "min_signals": 1,
        "description": "String matching and search",
    },
    "consistent_hashing": {
        "imports": ["hashring", "consistent_hash_ring", "jumphash", "mpchash"],
        "identifiers": [
            "hashring",
            "hash_ring",
            "consistent_hash",
            "virtual_node",
            "vnode",
            "jump_hash",
        ],
        "min_signals": 1,
        "description": "Consistent hashing",
    },
    "lfu_cache": {
        "imports": ["lfu", "lfu_cache", "tinylfu", "moka"],
        "identifiers": [
            "lfucache",
            "lfu_cache",
            "lfu",
            "tinylfu",
            "frequency_sketch",
            "access_count",
        ],
        "min_signals": 1,
        "description": "LFU cache",
    },
}

RUST_DESIGN_PATTERNS = {
    "api_design": {
        "imports": [
            "axum",
            "actix_web",
            "actix-web",
            "warp",
            "rocket",
            "tonic",
            "hyper",
            "poem",
            "salvo",
            "tide",
            "tower_http",
        ],
        "identifiers": [
            "router",
            "get",
            "post",
            "handler",
            "httpresponse",
            "statuscode",
            "route",
            "extractor",
        ],
        "min_signals": 2,
        "description": "HTTP/RPC API design",
    },
    "database_orm": {
        "imports": [
            "sqlx",
            "diesel",
            "sea_orm",
            "sea-orm",
            "rusqlite",
            "tokio_postgres",
            "tokio-postgres",
            "postgres",
            "mongodb",
            "redb",
            "sled",
            "rocksdb",
            "surrealdb",
            "mysql_async",
            "deadpool_postgres",
        ],
        "min_signals": 1,
        "description": "Database access layers",
    },
    "caching": {
        "imports": ["redis", "moka", "cached", "lru", "memcache", "fred"],
        "identifiers": [
            "cache",
            "cached",
            "redis",
            "ttl",
            "cache_get",
            "cache_set",
            "invalidate",
            "memoize",
        ],
        "min_signals": 1,
        "description": "Caching layer implementation",
    },
    "message_queue": {
        "imports": [
            "rdkafka",
            "lapin",
            "amqprs",
            "rumqttc",
            "paho_mqtt",
            "aws_sdk_sqs",
            "nats",
            "async_nats",
            "pulsar",
            "kafka",
            "redis::streams",
            "zeromq",
            "zmq",
        ],
        "min_signals": 1,
        "description": "Message queue/async processing",
    },
    "authentication": {
        "imports": [
            "jsonwebtoken",
            "argon2",
            "bcrypt",
            "oauth2",
            "openidconnect",
            "axum_login",
            "actix_identity",
            "biscuit_auth",
            "paseto",
            "rustls",
            "webauthn_rs",
        ],
        "identifiers": [
            "jwt",
            "claims",
            "authenticate",
            "authorize",
            "bearer",
            "access_token",
            "refresh_token",
            "password_hash",
            "verify_password",
        ],
        "min_signals": 1,
        "description": "Authentication/Authorization",
    },
    "logging": {
        "imports": [
            "log",
            "tracing",
            "env_logger",
            "tracing_subscriber",
            "slog",
            "fern",
            "flexi_logger",
            "simplelog",
        ],
        "identifiers": [
            "info",
            "warn",
            "error",
            "debug",
            "trace",
            "logger",
            "tracing",
            "instrument",
            "span",
        ],
        "min_signals": 2,
        "description": "Logging implementation",
    },
    "error_handling": {
        "imports": ["anyhow", "thiserror", "eyre", "color_eyre", "miette", "snafu", "failure"],
        "identifiers": [
            "result",
            "error",
            "err",
            "anyhow",
            "thiserror",
            "context",
            "with_context",
            "map_err",
            "from_residual",
            "question_mark",
        ],
        "text": [
            "?;",
            "map_err(",
            "impl std::error::error for",
            "impl error for",
            "#[derive(debug, thiserror::error)]",
        ],
        "min_signals": 2,
        "description": "Structured error handling",
    },
    "testing": {
        "imports": [
            "proptest",
            "quickcheck",
            "mockall",
            "rstest",
            "insta",
            "criterion",
            "assert_cmd",
            "wiremock",
            "httpmock",
            "fake",
            "test_case",
            "serial_test",
        ],
        "identifiers": [
            "assert_eq",
            "assert_ne",
            "mock",
            "proptest",
            "test_case",
            "fixture",
            "bench",
        ],
        "text": ["#[test]", "#[cfg(test)]", "#[tokio::test]", "#[rstest]", "#[bench]"],
        "min_signals": 1,
        "description": "Testing patterns",
    },
    "config_management": {
        "imports": [
            "config",
            "figment",
            "dotenvy",
            "dotenv",
            "envy",
            "clap",
            "serde_yaml",
            "toml",
            "confy",
        ],
        "identifiers": [
            "config",
            "settings",
            "env",
            "var",
            "environment",
            "from_env",
            "appconfig",
            "settings",
        ],
        "text": ["env::var(", "std::env::var("],
        "min_signals": 2,
        "description": "Configuration management",
    },
    "microservices": {
        "imports": [
            "tonic",
            "prost",
            "tarpc",
            "consul",
            "etcd_client",
            "etcd-client",
            "kube",
            "k8s_openapi",
            "opentelemetry",
        ],
        "identifiers": [
            "grpc",
            "service_discovery",
            "servicediscovery",
            "circuit_breaker",
            "sidecar",
            "healthcheck",
            "health_check",
            "readiness",
        ],
        "min_signals": 1,
        "description": "Microservices patterns",
    },
    "dependency_injection": {
        "imports": [
            "shaku",
            "inject",
            "axum::extract::state",
            "actix_web::web::data",
            "teloc",
            "coi",
        ],
        "identifiers": [
            "inject",
            "injectable",
            "container",
            "provider",
            "state",
            "appstate",
            "app_state",
            "dyn",
        ],
        "text": ["state<", "arc<dyn ", "box<dyn "],
        "min_signals": 2,
        "description": "Dependency injection",
    },
    "repository_pattern": {
        "identifiers": [
            "repository",
            "repo",
            "userrepository",
            "find_by_id",
            "find_all",
            "save",
            "delete_by_id",
            "store",
        ],
        "identifier_contains": ["repository", "_repo"],
        "text": ["trait userrepository", "repository for"],
        "min_signals": 1,
        "description": "Repository pattern for data access",
    },
    "factory_pattern": {
        "identifiers": ["factory", "create", "builder", "new", "from", "try_from", "default"],
        "identifier_contains": ["factory", "_factory"],
        "text": ["fn create(", "trait factory", "impl from<"],
        "min_signals": 2,
        "description": "Factory pattern: creation behind an interface",
    },
    "singleton_pattern": {
        "imports": [
            "once_cell",
            "lazy_static",
            "std::sync::oncelock",
            "std::sync::lazylock",
            "std::sync::once",
        ],
        "identifiers": [
            "oncecell",
            "oncelock",
            "lazylock",
            "lazy_static",
            "once",
            "get_or_init",
            "instance",
            "global",
        ],
        "text": ["lazy_static!", "static ref", "oncelock::new()", "once_cell::sync::lazy"],
        "min_signals": 1,
        "description": "Singleton: one shared instance",
    },
}

# Scoring policy 2.0.0: production-systems and GoF patterns, merged from the
# shared specs with Rust's idiomatic crates. Cargo dependencies are the
# strongest evidence in Rust code, so most anchors are ``use`` roots.
RUST_DSA_PATTERNS.update(
    {k: v for k, v in PRODUCTION_DSA_PATTERNS.items() if k not in RUST_DSA_PATTERNS}
)
RUST_DESIGN_PATTERNS.update(
    production_design_patterns(
        imports={
            "resilience": [
                "backoff",
                "tokio_retry",
                "tokio-retry",
                "again",
                "retry",
                "failsafe",
                "tower::retry",
                "tower::timeout",
                "circuit_breaker",
                "recloser",
            ],
            "rate_limiting": [
                "governor",
                "tower::limit",
                "leaky_bucket",
                "leaky-bucket",
                "ratelimit",
                "tower_governor",
                "ratelimit_meter",
            ],
            "observability": [
                "tracing",
                "opentelemetry",
                "prometheus",
                "metrics",
                "tracing_opentelemetry",
                "sentry",
                "tracing_subscriber",
                "metrics_exporter_prometheus",
                "console_subscriber",
            ],
            "event_sourcing_cqrs": [
                "cqrs_es",
                "cqrs-es",
                "eventually",
                "esrs",
                "thalo",
                "eventstore",
            ],
            "pagination": [],
            "concurrency": [
                "tokio",
                "async_std",
                "async-std",
                "smol",
                "rayon",
                "crossbeam",
                "std::sync",
                "std::thread",
                "parking_lot",
                "futures",
                "flume",
                "dashmap",
                "arc_swap",
                "std::sync::atomic",
                "tokio::sync",
            ],
            "dead_letter_outbox": ["lapin", "rdkafka", "aws_sdk_sqs"],
            "idempotency": [],
            "adapter_pattern": [],
            "builder_pattern": ["derive_builder", "typed_builder", "bon"],
            "decorator_pattern": [
                "tower",
                "tower::layer",
                "axum::middleware",
                "actix_web::middleware",
            ],
            "observer_pattern": [
                "tokio::sync::broadcast",
                "tokio::sync::watch",
                "crossbeam_channel",
                "event_listener",
                "bus",
            ],
            "strategy_pattern": [],
        },
        identifiers={
            "concurrency": [
                "spawn",
                "mutex",
                "rwlock",
                "arc",
                "atomic",
                "channel",
                "mpsc",
                "oneshot",
                "join_handle",
                "joinhandle",
                "async",
                "await",
                "select",
                "semaphore",
                "par_iter",
                "rayon",
            ],
            "resilience": [
                "retry",
                "backoff",
                "circuit_breaker",
                "circuitbreaker",
                "timeout",
                "with_timeout",
                "exponential_backoff",
                "fallback",
                "bulkhead",
            ],
            "rate_limiting": [
                "rate_limiter",
                "ratelimiter",
                "governor",
                "quota",
                "token_bucket",
                "leaky_bucket",
                "throttle",
                "throttled",
            ],
            "observability": [
                "instrument",
                "span",
                "counter",
                "histogram",
                "gauge",
                "metrics",
                "tracer",
                "meter",
                "register_int_counter",
            ],
            "event_sourcing_cqrs": [
                "event",
                "events",
                "aggregate",
                "command",
                "query",
                "projection",
                "event_store",
                "eventstore",
                "apply_event",
                "commandhandler",
                "queryhandler",
            ],
            "pagination": [
                "page",
                "page_size",
                "per_page",
                "limit",
                "offset",
                "cursor",
                "next_cursor",
                "has_more",
                "paginate",
                "paginated",
            ],
            "dead_letter_outbox": [
                "dead_letter",
                "deadletter",
                "dlq",
                "outbox",
                "poison",
                "redrive",
                "retry_queue",
            ],
            "idempotency": [
                "idempotency_key",
                "idempotent",
                "idempotency",
                "request_id",
                "seen_ids",
            ],
            "adapter_pattern": ["adapter", "wrapper", "port", "adapt", "into_inner", "as_ref"],
            "builder_pattern": [
                "builder",
                "build",
                "with_",
                "set_",
                "typedbuilder",
                "derive_builder",
            ],
            "decorator_pattern": [
                "layer",
                "middleware",
                "service_fn",
                "wrap",
                "decorate",
                "interceptor",
                "tower_layer",
            ],
            "observer_pattern": [
                "subscribe",
                "subscriber",
                "notify",
                "notify_all",
                "broadcast",
                "watch",
                "listener",
                "on_event",
                "emit",
            ],
            "strategy_pattern": [
                "strategy",
                "policy",
                "algorithm",
                "dyn",
                "impl_trait",
                "trait_object",
                "select_strategy",
            ],
        },
        text={
            "builder_pattern": [
                "#[derive(builder)]",
                "#[derive(typedbuilder)]",
                "::builder()",
                ".build()",
            ],
            "strategy_pattern": ["box<dyn ", "arc<dyn ", "&dyn "],
            "adapter_pattern": ["impl from<", "impl into<", "impl asref<"],
            "decorator_pattern": [
                "impl<s> layer<s> for",
                "impl<s> service<",
                "servicebuilder::new()",
            ],
            "observer_pattern": ["broadcast::channel(", "watch::channel(", ".subscribe()"],
        },
    )
)

# ``Vec::dedup`` is a std method, not an idempotency signal in Rust; drop the
# shared anchor so sorting-and-deduplicating a Vec does not claim the pattern.
RUST_DESIGN_PATTERNS["idempotency"]["identifiers"] = [
    name for name in RUST_DESIGN_PATTERNS["idempotency"]["identifiers"] if name != "dedup"
]
